### ISSUE TITLE
Chat - Start moving over what we had in Uplink before refactor 

### ISSUE THREAD

**Issue by phillsatellite** [Satellite-im/Uplink#307]
**Tasks:**
Stu had added a bunch of stuff into the messages/chat feature before we did the refactor. This ticket is to start implementing what we had into the new Uplink. 

- [x] Display most recent message sent or received with the timestamp in the Sidebar
- [x] User should be able to delete messages 
- User should eventually be able to edit messages, once supported by Warp
- [x] Users should be able to reply to each other with it indicating in chat that it is a reply
- [ ] User should be able to add a reaction to messages in chat
- [x] User should be able to send and receive files in chat
- [ ] If we have file sharing in chat we should probably _try_ to add file preview but this is just a thought!
- [x] typing indicator

**Comment by sdwoodbury** [comment]
note that the message timestamp in the sidebar currently doesn't get displayed if the user has no badge. it appears to be designed that way.

**Comment by sdwoodbury** [comment]
the back end is done for everything except edit/delete and send/receive files

**Comment by sdwoodbury** [comment]
just realized that RayGun doesn't allow for editing a message once it has been sent. perhaps that feature won't get implemented.

**Comment by sdwoodbury** [comment]
https://github.com/Satellite-im/Uplink/pull/335

**Comment by dariusc93** [comment]
> just realized that RayGun doesn't allow for editing a message once it has been sent. perhaps that feature won't get implemented.

You can edit a message by using `RayGun::send` with the message id of the message youre looking to edit. Honestly, I may go on and split it up into 2 functions down the road to prevent confusion

EDIT: Also, a lot of functionality been added to the rg-ipfs example. Eg, editing messages can be found at https://github.com/Satellite-im/Warp/blob/main/extensions/warp-rg-ipfs/examples/messenger.rs#L722
